### ISSUE TITLE
jinja2.exceptions.TemplateNotFound

### ISSUE THREAD

**Issue by joaroque** [hoh/perfume#2]
render_template return error

**Comment by hoh** [comment]
Hi @joaroque, can you please explain the issue in more details ?

- What you were trying to do
- The version of Python, Flask and perfume you were using

**Comment by joaroque** [comment]
I am trying to render the html of a parameter of the perfume class but it gives error when rendering.

Can you please show me an example of how to render html with **Perfume** or is it just for **APIs**?

I'm using python 3
The recent version of **Perfume**

**Comment by hoh** [comment]
This should work now, see the updated README.
